"use strict";

class Images {
    constructor() { }

    static tileImages = Util.loadImages("tiles/", [
        "plains",
        "island",
        "swamp",
        "mountain",
        "forest",
        "city",
        "fog_of_war",
        "broussailles",
        "butte",
        "friche",
        "greve",
        "landes",
        "desert"
    ]);

    static unitImages = Util.loadImages("units/", [
        "explorer",
        "campfire"
    ]);

    static resourceImages = Util.loadImages("resources/", [
        "concrete",
        "electronics",
        "iron_ore",
        "ancient_metal",
        "ancient_plastic",
        "ancient_glass",
        "water",
        "wood",
        "oil",
        "unknownResource",
        "fruits",
        "mushrooms",
        "clay",
        "sandstone",
        "plants",
        "sand",
        "copper_ore",
        "limestone",
        "lumber",
        "flint",
        "wild_wheat",
        "seeds",
        "wheat",
        "charcoal",
        "clean_water",
        "science",
        "soap",
        "compost",
        "ash",
        "glass",
        "iron",
        "tool",
        "clothes",
        "rope",
        "wool",
        "sail",
        "ceramics",
        "pottery",
        "soil",
        "animals",
        "domesticated_animals",
        "meat",
        "bricks",
        "medicinal_plants",
        "medicine",
        "flour",
        "dough",
        "bread",
        "hide",
        "leather",
        "plant_fibers",
        "string",
        "grain",
        "beer",
        "resin",
        "mortar",
        "plaster",
        "containers",
        "lime",
        "saltwater",
        "salt",
        "bronze",
        "copper",
        "steel",
        "preserved_food"
    ]);
}