"use strict";

// document.body.innerText = JSON.stringify(Object.fromEntries(
//     Object.entries(Data.knowledges).sort(([a], [b]) => Data.knowledges[a].localeCompare(Data.knowledges[b]))
// ), null, 4);

class Data {
    static defaultPopGrowth = 5;
    static defaultFatigue = 5;
    static defaultFatigueRecovery = 2;
    static defaultRegeneration = 1;
    static resources =
        {
            // -------------------------- WIP --------------------------
            "water": "eau",
            "wood": "bois",
            "fruit": "fruits",
            // -------------------------- images available --------------------------
            // "concrete": "béton",
            // "electronics": "électronique",
            // "iron": "fer",
            // "metal": "métal",
            // "plastic": "plastique",
            // "oil": "pétrole",
            // -------------------------- images unavailable --------------------------
            // [][][][][][][][][] TODO [][][][][][][][][]

            // [][][][][][][][][] céréales [][][][][][][][][]
            // "wild_grass": "herbes sauvages",
            // "wild_wheat": "blé sauvage",
            // "wild_barley": "orge sauvage",
            // "wild_rye": "seigle sauvage",
            // "wild_oats": "avoine sauvage",
            // "wild_millet": "millet sauvage",
            // "wild_spelt": "épeautre sauvage",
            // "wheat": "blé",
            // "barley": "orge",
            // "rye": "seigle",
            // "oats": "avoine",
            // "millet": "millet",
            // "spelt": "épeautre",
            // "grain": "grain",
            // "flour": "farine",
            // "bran": "son",
            // "straw": "paille",
            // "malt": "malt",
            // "bread": "pain",
            // "porridge": "bouillie",
            // "flatbread": "galette",
            // "beer": "bière",
            // [][][][][][][][][] naturelles [][][][][][][][][]
            // wheat: "blé",
            // barley: "orge",
            // rye: "seigle",
            // oats: "avoine",
            // millet: "millet",
            // "silver": "argent",
            // "clay": "argile",
            // "limestone": "calcaire",
            // "rubber": "caoutchouc",
            // "coal": "charbon",
            // "copper": "cuivre",
            // "rainwater": "eau de pluie",
            // "freshwater": "eau douce",
            // "saltwater": "eau salée",
            // "bark": "écorce",
            // "tin": "étain",
            // "nickel": "nickel",
            // "gold": "or",
            // "stone": "pierre",
            // "plants": "plantes",
            // "medicinal_plants": "plantes médicinales",
            // "lead": "plomb",
            // "quartz": "quartz",
            // "resin": "résine",
            // "sand": "sable",
            // "salt": "sel",
            // "zinc": "zinc"
            // "natural_gas": "gaz naturel",
            // "graphite": "graphite",
            // [][][][][][][][][] fabriquées [][][][][][][][][]
            // "lumber": "bois d'œuvre",
            // "bricks": "briques",
            // "ceramics": "céramique",
            // "charcoal": "charbon de bois",
            // "leather": "cuir",
            // "cultures": "cultures",
            // "groundwater": "eau souterraine",
            // "fertilizer": "engrais",
            // "fibers": "fibres",
            // "food": "nourriture",
            // "tools": "outils",
            // "seeds": "semences",
            // "rare_earths": "terres rares",
            // "glass": "verre",
            // "meat": "viande",
            // [][][][][][][][][] vestiges   [][][][][][][][][]
            // "aluminium": "aluminium",
            // "steel": "acier",
            // "batteries": "batteries",
            // "fuel": "carburant",
            // "cement": "ciment",
            // "machinery": "machines",
            // "microchips": "microprocesseurs",
            // "engines": "moteurs",
            // "computers": "ordinateurs",
            // "polymers": "polymères",
            // "chemicals": "produits chimiques",
            // "radios": "radios",
            // "vehicles": "véhicules",
        }
    static actions = {
        // céréales
        // "observe": "observer",
        // "identify": "identifier",
        // "gather": "ramasser",
        // "collect_seeds": "récolter des semences",
        // "inspect": "examiner",
        // "compare": "comparer",
        // "clear_land": "défricher",
        // "prepare_soil": "préparer le sol",
        // "plant": "planter",
        // "sow": "semer",
        // "water": "arroser",
        // "weed": "désherber",
        // "fertilize": "fertiliser",
        // "harvest": "récolter",
        // "select_seeds": "sélectionner les semences",
        // "thresh": "battre",
        // "winnow": "vanner",
        // "grind": "moudre",
        // "mill": "utiliser un moulin",
        // "mix": "mélanger",
        // "knead": "pétrir",
        // "bake": "cuire",
        // "ferment": "fermenter",
        // "malt": "malter",
        // "dry": "sécher",
        // "store": "stocker",
        // "cultivate": "cultiver",
        // "farm": "exploiter une terre agricole",
        // "harvest_automatically": "récolter automatiquement",
        // "irrigate": "irriguer",
        // "rotate_crops": "pratiquer la rotation des cultures",
        // "maintain_field": "entretenir une parcelle",
        // "abandon_field": "abandonner une parcelle",
        "fell": "abattre",
        "fetch": "aller chercher",
        "alloy": "allier",
        "upgrade": "améliorer",
        "analyze": "analyser",
        "tame": "apprivoiser",
        "survey": "arpenter",
        "water": "arroser",
        "allocate": "attribuer",
        "dam": "barrer",
        "boil_water": "bouillir",
        "crush": "broyer",
        "burn": "brûler",
        "map": "cartographier",
        "catalogue": "cataloguer",
        "hunt": "chasser",
        "classify": "classer",
        "collect": "collecter",
        "combine": "combiner",
        "compare": "comparer",
        "compost": "composter",
        "compress": "compresser",
        "cast": "couler",
        "cut": "couper",
        "dig": "creuser",
        "breed": "croiser",
        "gather": "cueillir",
        "cultivate": "cultiver",
        "decontaminate": "décontaminer",
        "clear": "défricher",
        "demolish": "démolir",
        "dismantle": "démonter",
        "relocate": "déplacer",
        "strip": "dépouiller",
        "weed": "désherber",
        "desalinate": "dessaler",
        "detect": "détecter",
        "divert": "détourner",
        "destroy": "détruire",
        "distill": "distiller",
        "record": "documenter",
        "domesticate": "domestiquer",
        "dredge": "draguer",
        "drain": "drainer",
        "sample": "échantillonner",
        "hypothesize": "émettre une hypothèse",
        "tap": "entailler",
        "store": "entreposer",
        "study": "étudier",
        "experiment": "expérimenter",
        "quarry": "exploiter",
        "explore": "explorer",
        "extract": "extraire",
        "melt": "faire fondre",
        "rotate_crops": "faire une rotation des cultures",
        "ferment": "fermenter",
        "fertilize": "fertiliser",
        "filter_water": "filtrer",
        "smelt": "fondre",
        "drill": "forer",
        "forge": "forger",
        "scavenge": "fouiller",
        "identify": "identifier",
        "inspect": "inspecter",
        "irrigate": "irriguer",
        "isolate": "isoler",
        "wash": "laver",
        "limit": "limiter",
        "locate": "localiser",
        "measure": "mesurer",
        "quarantine": "mettre en quarantaine",
        "mine": "miner",
        "model": "modéliser",
        "clean": "nettoyer",
        "observe": "observer",
        "fish": "pêcher",
        "trap": "piéger",
        "plant": "planter",
        "pump": "pomper",
        "scoop": "prélever",
        "strip_bark": "prélever l'écorce",
        "preserve": "préserver",
        "prospect": "prospecter",
        "protect": "protéger",
        "draw": "puiser",
        "purify": "purifier",
        "refine": "raffiner",
        "collect": "ramasser",
        "ration": "rationner",
        "reforest": "reboiser",
        "research": "rechercher",
        "harvest": "récolter",
        "collect_resin": "récolter la résine",
        "collect_fibers": "récolter les fibres",
        "collect_seeds": "récolter les graines",
        "scout": "reconnaître",
        "collect_rainwater": "recueillir",
        "salvage": "récupérer",
        "recycle": "recycler",
        "reduce": "réduire",
        "rewild": "réensauvager",
        "regulate": "réguler",
        "reclaim": "réhabiliter",
        "release": "relâcher",
        "reinforce": "renforcer",
        "repair": "réparer",
        "replant": "replanter",
        "restore": "restaurer",
        "restore_habitat": "restaurer l'habitat",
        "repurpose": "réutiliser",
        "select": "sélectionner",
        "sow": "semer",
        "separate": "séparer",
        "sequence": "séquencer",
        "simulate": "simuler",
        "stockpile": "stocker",
        "track": "suivre",
        "monitor": "surveiller",
        "prune": "tailler",
        "pan": "tamiser",
        "test": "tester",
        "process": "transformer",
        "transport": "transporter",
        "sort": "trier"
    }
    static knowledges =
        {
            // céréales
            // "wild_grass_identification": "identification des herbes sauvages",
            // "wild_grain_identification": "identification des céréales sauvages",
            // "seed_collection": "collecte des semences",
            // "grain_maturation": "maturation des grains",
            // "grain_seasons": "cycles saisonniers des céréales",
            // "plant_propagation": "propagation des plantes",
            // "plant_selection": "sélection des plantes",
            // "seed_planting": "plantation des semences",
            // "soil_preparation": "préparation du sol",
            // "crop_cultivation": "culture des plantes",
            // "crop_selection": "sélection des cultures",
            // "crop_rotation": "rotation des cultures",
            // "weed_management": "gestion des plantes concurrentes",
            // "irrigation": "irrigation",
            // "harvesting_seasons": "saisons des récoltes",
            // "grain_processing": "transformation des grains",
            // "grinding": "mouture",
            // "flour_production": "production de farine",
            // "dough_making": "préparation de la pâte",
            // "baking": "cuisson au four",
            // "fermentation": "fermentation",
            // "malting": "maltage",
            // "selective_breeding": "sélection génétique",
            // "seed_storage": "conservation des semences",
            // "crop_diversification": "diversification des cultures",
            // "soil_fertility": "fertilité des sols",
            // "fertilization": "fertilisation",
            // "agricultural_planning": "planification agricole",
            // "grain_storage": "stockage des grains",
            // "drying": "séchage",
            // "food_preservation": "conservation des aliments",
            // "granaries": "greniers",
            // "food_surplus": "surplus alimentaire",
            // "food_distribution": "distribution alimentaire",
            "starter": "starter",
            "acids_and_bases": "acides et bases",
            "agriculture": "agriculture",
            "agroforestry": "agroforesterie",
            "alloys": "alliages",
            "water_testing": "analyse de l'eau",
            "anatomy": "anatomie",
            "archaeology": "archéologie",
            "architecture": "architecture",
            "sanitation": "assainissement",
            "aerospace": "astronautique",
            "astronomy": "astronomie",
            "automation": "automatisation",
            "watersheds": "bassins versants",
            "batteries": "batteries",
            "concrete": "béton",
            "biofuels": "biocarburants",
            "biochemistry": "biochimie",
            "biodiversity": "biodiversité",
            "biology": "biologie",
            "botany": "botanique",
            "carrying_capacity": "capacité de charge",
            "sensors": "capteurs",
            "cartography": "cartographie",
            "catalysis": "catalyse",
            "ceramics": "céramiques",
            "supply_chains": "chaînes d'approvisionnement",
            "chemistry": "chimie",
            "inorganic_chemistry": "chimie minérale",
            "organic_chemistry": "chimie organique",
            "climatology": "climatologie",
            "water_collection": "collecte de l'eau",
            "fossil_fuels": "combustibles fossiles",
            "combustion": "combustion",
            "composting": "compostage",
            "conservation": "conservation",
            "water_conservation": "conservation de l'eau",
            "quality_control": "contrôle qualité",
            "corrosion": "corrosion",
            "rivers": "cours d'eau",
            "nitrogen_cycle": "cycle de l'azote",
            "water_cycle": "cycle de l'eau",
            "carbon_cycle": "cycle du carbone",
            "nutrient_cycles": "cycles des nutriments",
            "desalination": "dessalement",
            "water_detection": "détection de l'eau",
            "seed_dispersal": "dispersion des graines",
            "distillation": "distillation",
            "domestication": "domestication",
            "groundwater": "eaux souterraines",
            "ecology": "écologie",
            "freshwater_ecology": "écologie des eaux douces",
            "soil_ecology": "écologie des sols",
            "wetland_ecology": "écologie des zones humides",
            "forest_ecology": "écologie forestière",
            "economics": "économie",
            "ecosystems": "écosystèmes",
            "writing": "écriture",
            "education": "éducation",
            "electricity": "électricité",
            "electromagnetism": "électromagnétisme",
            "electronics": "électronique",
            "energy": "énergie",
            "wind_power": "énergie éolienne",
            "geothermal_energy": "énergie géothermique",
            "hydropower": "énergie hydraulique",
            "solar_power": "énergie solaire",
            "entomology": "entomologie",
            "epidemiology": "épidémiologie",
            "invasive_species": "espèces invasives",
            "evolution": "évolution",
            "quarrying": "exploitation de carrières",
            "mining": "exploitation minière",
            "manufacturing": "fabrication",
            "fermentation": "fermentation",
            "fertilization": "fertilisation",
            "water_filtration": "filtration de l'eau",
            "habitat_fragmentation": "fragmentation des habitats",
            "genetics": "génétique",
            "chemical_engineering": "génie chimique",
            "electrical_engineering": "génie électrique",
            "mechanical_engineering": "génie mécanique",
            "geochemistry": "géochimie",
            "geography": "géographie",
            "geology": "géologie",
            "soil_management": "gestion des sols",
            "sustainable_management": "gestion durable",
            "ore_deposits": "gisements minéraux",
            "governance": "gouvernance",
            "history": "histoire",
            "horticulture": "horticulture",
            "hydrology": "hydrologie",
            "hydroponics": "hydroponie",
            "environmental_impact": "impact environnemental",
            "computing": "informatique",
            "engineering": "ingénierie",
            "species_interactions": "interactions entre espèces",
            "irrigation": "irrigation",
            "limnology": "limnologie",
            "logistics": "logistique",
            "pest_control": "lutte contre les nuisibles",
            "composites": "matériaux composites",
            "mathematics": "mathématiques",
            "medicine": "médecine",
            "metallurgy": "métallurgie",
            "smelting": "métallurgie extractive",
            "meteorology": "météorologie",
            "microbiology": "microbiologie",
            "mineralogy": "minéralogie",
            "mycology": "mycologie",
            "aquifers": "nappes phréatiques",
            "navigation": "navigation",
            "nutrition": "nutrition",
            "oceanography": "océanographie",
            "optics": "optique",
            "ornithology": "ornithologie",
            "paleontology": "paléontologie",
            "pathology": "pathologie",
            "soil_science": "pédologie",
            "permaculture": "permaculture",
            "pharmacology": "pharmacologie",
            "physiology": "physiologie",
            "herbal_medicine": "phytothérapie",
            "plastics": "plastiques",
            "pollination": "pollinisation",
            "polymers": "polymères",
            "industrial_processes": "procédés industriels",
            "mass_production": "production de masse",
            "programming": "programmation",
            "prospecting": "prospection",
            "wells": "puits",
            "water_purification": "purification de l'eau",
            "radio": "radio",
            "material_recovery": "récupération des matériaux",
            "recycling": "recyclage",
            "regeneration": "régénération",
            "power_grids": "réseaux électriques",
            "food_webs": "réseaux trophiques",
            "restoration_ecology": "restauration écologique",
            "robotics": "robotique",
            "crop_rotation": "rotation des cultures",
            "materials_science": "science des matériaux",
            "seed_selection": "sélection des semences",
            "plant_breeding": "sélection végétale",
            "greenhouses": "serres",
            "steelmaking": "sidérurgie",
            "solvents": "solvants",
            "springs": "sources",
            "statistics": "statistiques",
            "sterilization": "stérilisation",
            "water_storage": "stockage de l'eau",
            "energy_storage": "stockage de l'énergie",
            "stratigraphy": "stratigraphie",
            "succession": "succession écologique",
            "stoneworking": "taille de pierre",
            "taxonomy": "taxonomie",
            "telecommunications": "télécommunications",
            "urban_planning": "urbanisme",
            "machining": "usinage",
            "glassmaking": "verrerie",
            "zoology": "zoologie"
        }
}